version: 2

sources:
    - name: src_jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers        
            identifier: customers  
            description: One record per customer.
          - name: orders       
            identifier: orders 
            description: One record per order. Includes cancelled and deleted orders.